'use client';

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'pt' | 'es';

interface Translations {
  [key: string]: {
    [key: string]: string;
  };
}

const translations: Translations = {
  en: {
    // Navbar
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.programs': 'Programs',
    'nav.sponsorship': 'Sponsorship',
    'nav.resources': 'Resources',
    'nav.tryouts': 'Tryouts',
    'nav.contact': 'Contact',
    'nav.register': 'Register Now',

    // Resources Page
    'resources.title': 'Parent & Player Resources',
    'resources.subtitle': 'Important documents, policies, and information for our academy families.',
    'resources.doc1.title': 'Zero Tolerance Approved',
    'resources.doc1.desc': 'Our guidelines on behavior, zero tolerance policy, and expectations for players, parents, and coaches.',
    'resources.doc2.title': 'Age Group Formation',
    'resources.doc2.desc': 'Information regarding age group formation and player development pathways.',
    'resources.viewBtn': 'View Document',
    
    // Hero Section
    'hero.title1': 'Where Champions',
    'hero.title2': 'Are Built',
    'hero.subtitle': 'Elite youth soccer development in Metro Charleston, SC',
    'hero.cta.primary': 'Register Now',
    'hero.cta.secondary': 'View Programs',
    'hero.marquee.1': 'Junior Academy',
    'hero.marquee.2': 'Select',
    'hero.marquee.3': 'Elite',
    'hero.marquee.4': 'Futsal',
    'hero.marquee.5': 'Summer Camps',
    'hero.marquee.6': 'U4 TO U18',
    
    // AcademyHeroVisual
    'visual.quote': 'Developing the next generation of players.',
    'visual.card1.title': 'Elite',
    'visual.card1.subtitle': 'Training',
    'visual.card3.title': 'Pro Pathway',
    
    // Lead Form
    'form.title': 'Get in Touch',
    'form.subtitle': 'Interested in joining BISA? Fill out the form below and our team will get back to you.',
    'form.parentName': 'Parent/Guardian Name',
    'form.email': 'Email Address',
    'form.phone': 'Phone Number',
    'form.playerName': 'Player Name',
    'form.birthYear': 'Player Birth Year',
    'form.program': 'Program of Interest',
    'form.program.notSure': 'Not Sure Yet',
    'form.message': 'Message / Questions',
    'form.messagePlaceholder': 'How can we help you?',
    'form.submit': 'Send Message',
    'form.success.title': 'Message Sent!',
    'form.success.message': 'Thank you for reaching out. We will contact you shortly.',
    'form.success.button': 'Send another message',
    'form.error': 'There was an error sending your message. Please try again later.',

    // Projeto BILU
    'projetobilu.label': '// SOCIAL PROJECT',
    'projetobilu.title': 'Football That Transforms Lives',
    'projetobilu.subtitle': 'Projeto BILU is a global humanitarian initiative that uses football as a tool for social transformation, present in 10 countries and impacting children worldwide.',
    'projetobilu.stat1.value': '15K+',
    'projetobilu.stat1.label': 'Kids Worldwide',
    'projetobilu.stat2.value': '12K+',
    'projetobilu.stat2.label': 'Kids in Brazil',
    'projetobilu.stat3.value': '10',
    'projetobilu.stat3.label': 'Countries',
    'projetobilu.stat4.value': '23',
    'projetobilu.stat4.label': 'Centers',
    'projetobilu.stat5.value': '153+',
    'projetobilu.stat5.label': 'Volunteers',
    'projetobilu.cta': 'Discover the Project',

    // Academy CTA
    'academycta.title': 'Ready to Elevate Your Game?',
    'academycta.subtitle': 'Join the premier youth soccer academy in Charleston',
    'academycta.btn': 'Explore Programs',
    'academycta.badge1': 'Global Elite Methodology',
    'academycta.badge2': 'Pro Coaching Staff',
    'academycta.badge3': 'U4 to U18 Programs',

    // Sponsors
    'sponsors.title': 'Our Partners & Sponsors',
    'sponsors.subtitle': 'Proudly supported by organizations that believe in the power of youth development and social transformation.',
    'sponsors.comingSoon': 'Coming Soon',
    'sponsors.becomePartner': 'Become a Partner',

    // Projeto BILU Page
    'pb.hero.sub1': 'Football as an instrument of',
    'pb.hero.sub2': 'human transformation',
    'pb.scroll': 'Discover',
    'pb.whatis.title': 'What Is ',
    'pb.whatis.titleHighlight': 'Projeto BILU?',
    'pb.whatis.p1': 'Projeto BILU is a global social initiative founded by Coach PC that uses football as a tool to ensure a dignified childhood for vulnerable children around the world.',
    'pb.whatis.p2.1': 'We operate with permanent centers in ',
    'pb.whatis.p2.2': '10 countries',
    'pb.whatis.p2.3': ' and point-in-time humanitarian campaigns in ',
    'pb.whatis.p2.4': '13 others',
    'pb.whatis.p2.5': ', with an army of volunteers passionate about transforming lives.',
    'pb.numbers.title': 'Impact in Numbers',
    'pb.numbers.l1': 'Countries with Centers',
    'pb.numbers.l2': 'Countries with Campaigns',
    'pb.numbers.l3': 'Countries Reached',
    'pb.numbers.l4': 'Volunteers (Brazil only)',
    'pb.numbers.l5': 'Centers in Brazil',
    'pb.global.title': 'Global Presence',
    'pb.global.desc': 'Where we operate our 10 permanent centers promoting inclusion through sports.',
    'pb.global.otherTitle': 'Humanitarian Campaigns in 13 Countries',
    'pb.global.otherDesc': 'Bolivia, Colombia, Uruguay, Paraguay, Costa Rica, El Salvador, Nicaragua, Senegal, Mozambique, Angola, Guinea-Bissau and 2 more...',
    'pb.brazil.title': 'Brazil in Detail',
    'pb.brazil.desc': 'Distribution of our 17 centers across the Brazilian territory.',
    'pb.brazil.centers': 'Centers',
    'pb.brazil.volunteers': 'Volunteers',
    'pb.actions.title': 'What We Do',
    'pb.actions.1.title': 'Solidarity Christmas',
    'pb.actions.1.desc': 'Gathering and delivering toys and food for vulnerable families.',
    'pb.actions.2.title': 'Happy Easter',
    'pb.actions.2.desc': 'Distributing chocolates and messages of hope in supported communities.',
    'pb.actions.3.title': 'Social Projects',
    'pb.actions.3.desc': 'Continuous community actions working on moral, educational, and civic foundations.',
    'pb.actions.4.title': 'Humanitarian Campaigns',
    'pb.actions.4.desc': 'Support and humanitarian aid in regions impacted by crises and disasters worldwide.',
    'pb.actions.5.title': 'Child Development',
    'pb.actions.5.desc': 'Football as the main master tool in physical and cognitive child development.',
    'pb.gallery.title': 'Our Gallery',
    'pb.gallery.desc': 'Unforgettable moments in our centers across Brazil and the world.',
    'pb.gallery.soon': 'Coming Soon',
    'pb.cta.title': 'Be Part of this Transformation',
    'pb.cta.btn1': 'Be a Volunteer',
    'pb.cta.btn2': 'Back to Site',

    // Summer Camps Page
    'sc.hero.badge': 'JUNE & JULY · SANGAREE MIDDLE SCHOOL',
    'sc.hero.title1': 'BISA',
    'sc.hero.title2': 'SUMMER CAMPS',
    'sc.hero.subtitle': 'Two trainings per week. An intramural tournament. A summer your child will never forget.',
    'sc.hero.btn1': 'SECURE YOUR SPOT \u2192',
    'sc.hero.btn2': 'SEE PROGRAM DETAILS',
    
    'sc.ticker.1': 'Sangaree Middle School',
    'sc.ticker.2': 'June & July',
    'sc.ticker.3': '2x Per Week',
    'sc.ticker.4': 'Intramural Tournament',
    'sc.ticker.5': 'Limited Spots',
    'sc.ticker.6': 'Open Registration',

    'sc.overview.badge': 'The Program',
    'sc.overview.title': 'PROGRAM OVERVIEW',
    'sc.ov.1.title': 'June & July',
    'sc.ov.1.desc': 'Two full months of elite soccer development',
    'sc.ov.2.title': 'Sangaree Middle School',
    'sc.ov.2.desc': 'Convenient, safe, and familiar location',
    'sc.ov.3.title': '2x Per Week',
    'sc.ov.3.desc': 'Consistent training rhythm that builds real skills',
    'sc.ov.4.title': 'Intramural Tournament',
    'sc.ov.4.desc': 'Compete, win, grow — all within the camp community',

    'sc.features.title': 'WHAT YOUR CHILD WILL EXPERIENCE',
    'sc.feat.1.title': 'Elite Coaching',
    'sc.feat.1.desc': 'Certified coaches with international experience and real passion for player development',
    'sc.feat.2.title': 'Skill Development',
    'sc.feat.2.desc': 'Technical, tactical, and physical training adapted to every age and level',
    'sc.feat.3.title': 'Team Culture',
    'sc.feat.3.desc': 'Build friendships, learn to communicate, and grow as part of a real team',
    'sc.feat.4.title': 'Intramural Tournament',
    'sc.feat.4.desc': 'Every player competes in our internal championship — the highlight of the camp',
    'sc.feat.5.title': 'Safe Environment',
    'sc.feat.5.desc': 'Full supervision, inclusive atmosphere, and care for every individual',
    'sc.feat.6.title': 'Summer Memories',
    'sc.feat.6.desc': 'Games, laughs, growth — an experience that goes way beyond the pitch',

    'sc.global.title1': 'A GLOBAL COMMUNITY, ',
    'sc.global.title2': 'TRAINING TOGETHER',
    'sc.global.desc': 'Our players come from all over the world — soccer is the only language that matters.',

    'sc.join.title1': 'HOW TO ',
    'sc.join.title2': 'JOIN',
    'sc.step.1.num': '01',
    'sc.step.1.title': 'Click Register',
    'sc.step.1.desc': 'Hit the button and fill out the quick sign-up form on PlayMetrics',
    'sc.step.2.num': '02',
    'sc.step.2.title': 'Confirm Your Spot',
    'sc.step.2.desc': 'You\'ll receive a confirmation with all details about location and schedule',
    'sc.step.3.num': '03',
    'sc.step.3.title': 'Show Up Ready',
    'sc.step.3.desc': 'Bring cleats, shin guards, and your best attitude — we handle the rest',
    'sc.step.4.num': '04',
    'sc.step.4.title': 'Play. Compete. Grow.',
    'sc.step.4.desc': 'Train twice a week and compete in our intramural tournament',
    'sc.join.btn': 'REGISTER NOW \u2192',

    'sc.faq.title': 'FREQUENTLY ASKED QUESTIONS',
    'sc.faq.1.q': 'Who can participate?',
    'sc.faq.1.a': 'The camp is open to players of all skill levels. If your child loves soccer, they belong here.',
    'sc.faq.2.q': 'Where exactly is the camp?',
    'sc.faq.2.a': 'Sangaree Middle School. Address and parking details are sent after registration.',
    'sc.faq.3.q': 'How often are the sessions?',
    'sc.faq.3.a': 'Twice per week throughout June and July.',
    'sc.faq.4.q': 'What is the Intramural Tournament?',
    'sc.faq.4.a': 'At the end of the camp, all players compete in an internal championship organized within our own camp community. Every player gets to compete.',
    'sc.faq.5.q': 'What should my child bring?',
    'sc.faq.5.a': 'Cleats, shin guards, socks, water bottle, and athletic clothing. A full list is sent by email after sign-up.',
    'sc.faq.6.q': 'How do I register?',
    'sc.faq.6.a': 'Click any Register button on this page to be redirected to our secure sign-up form on PlayMetrics.',

    'sc.cta.badge': 'Don\'t wait',
    'sc.cta.title': 'DON\'T LET YOUR CHILD MISS THIS SUMMER',
    'sc.cta.subtitle': 'Limited spots available. June & July at Sangaree Middle School.',
    'sc.cta.btn': 'REGISTER NOW \u2192',
    'sc.cta.micro': 'Quick sign-up via PlayMetrics · Secure & easy',

    // Sponsorship Page
    'sp.hero.title1': 'CLUB SPONSORSHIP',
    'sp.hero.title2': 'PACKAGES',
    'sp.hero.scroll': 'Scroll to explore',
    'sp.hero.quote': 'You\'re not just placing your logo on the field — you\'re opening doors for talented young players who, thanks to your support, can pursue their dreams and build a better life through sports.',
    'sp.impact.title': 'More Than Sponsorship.',
    'sp.impact.titleHighlight': 'It\'s Transformation.',
    'sp.impact.desc': 'By becoming a sponsor, you\'re not only supporting the academy — you\'re helping BISA continue its mission of creating real opportunities for children around the world.',
    'sp.impact.callout': 'Thanks to sponsor support, BISA has grown from $7,214 in financial aid to over $50,000 this season.',
    'sp.impact.stat.current': 'Current Season',
    'sp.impact.footer': 'Each contribution helps children from different countries access soccer, education, and life-changing experiences.',
    'sp.jersey.badge': '✨ Premium Sponsorship',
    'sp.jersey.title1': 'Official Jersey',
    'sp.jersey.title2': 'Sponsorship',
    'sp.jersey.front': 'Front — Shirt Sponsor',
    'sp.jersey.sleeve': 'Back/Sleeve — Sleeve Sponsor',
    'sp.jersey.benefit1': 'Your logo on competition jerseys — max visibility',
    'sp.jersey.benefit2': 'Constant presence in photos, videos and social media',
    'sp.jersey.benefit3': 'Direct funding for student-athlete scholarships',
    'sp.jersey.benefit4': 'Total association with a community-first brand',
    'sp.packages.transitionTitle1': 'AVAILABLE SPONSORSHIP',
    'sp.packages.transitionTitle2': 'PACKAGES',
    'sp.bundle.badge': 'The Ultimate Connection',
    'sp.bundle.title1': 'BISA BUNDLE',
    'sp.bundle.title2': 'PACKAGE',
    'sp.bundle.desc': 'Why settle for one when you can dominate every front? Our Bundle Package combines all field and digital assets for maximum community impact.',
    'sp.bundle.benefit.hudl': 'Hudl Live Ads',
    'sp.bundle.hudl.chk1': 'Digital advertising banner',
    'sp.bundle.hudl.chk2': 'Live broadcast reach',
    'sp.bundle.hudl.chk3': 'Global family exposure',
    'sp.bundle.hudl.chk4': 'Digital brand recognition',
    'sp.bundle.benefit.banner': 'Field Banner (8x4)',
    'sp.bundle.banner.chk1': 'Standard 8\' x 4\' size',
    'sp.bundle.banner.chk2': 'Premium field placement',
    'sp.bundle.banner.chk3': 'Daily parent visibility',
    'sp.bundle.banner.chk4': 'QR Code direct traffic',
    'sp.bundle.benefit.flag': 'Club Flag (Event)',
    'sp.bundle.flag.chk1': 'Vertical branded flag',
    'sp.bundle.flag.chk2': 'Mobile event presence',
    'sp.bundle.flag.chk3': 'Tournament visibility',
    'sp.bundle.flag.chk4': 'Multi-location branding',
    'sp.bundle.benefit.priority': 'Priority Placement',
    'sp.bundle.asset.checklist': 'ASSET CHECKLIST:',
    'sp.bundle.asset.quote': 'This asset is meticulously designed to represent your brand during peak activity hours, ensuring every parent and athlete recognizes your contribution to the academy.',
    'sp.bundle.save': 'SAVE $1,000 SPECIAL',
    'sp.hudl.badge': '🎥 Digital Presence',
    'sp.hudl.title': 'Hudl Live Stream Broadcasting',
    'sp.hudl.desc': 'Your brand front and center during every live-streamed game. Reach families, fans, and supporters anywhere in the world.',
    'sp.flag.badge': 'Premium Branding',
    'sp.flag.title': 'Flag Sponsorship',
    'sp.flag.desc': 'A high-visibility vertical flag featuring your brand, prominently displayed at the training center and taken to every club match.',
    'sp.banner.badge': 'Field Presence',
    'sp.banner.title': 'Banner Sponsorship',
    'sp.banner.desc': 'Strategically positioned 8\' x 4\' banner at our training field, seen daily by parents and athletes.',
    'sp.why.badge': 'Community & Growth',
    'sp.why.title': 'Why Partner With BISA?',
    'sp.why.stat.athletes': 'Athletes',
    'sp.why.stat.families': 'Families',
    'sp.why.stat.weekly': 'Weekly Reach',
    'sp.why.stat.coverage': 'Social Coverage',
    'sp.packages.title1': 'Choose Your',
    'sp.packages.title2': 'Package',
    'sp.packages.desc': 'Exclusive opportunities to showcase your brand while supporting the athletic and social development of young players.',
    'sp.nonprofit.title': '501(c)(3) Nonprofit Organization',
    'sp.nonprofit.desc': 'Bilu International Soccer Academy is a registered 501(c)(3) nonprofit. Any donations or sponsorships may be tax-deductible. Feel free to reach out for a receipt or letter for tax purposes.',
    'sp.cta.title1': 'YOUR LOGO WILL STAND',
    'sp.cta.title2': 'BESIDE SPORTS EXCELLENCE',
    'sp.cta.subtitle': 'CONTACT US TO GUARANTEE YOUR SPACE!',
    'sp.contact.info': 'Contact Information',
    'sp.contact.more': 'More Information',
    'sp.contact.visit': 'Visit our website',
    'sp.contact.scan': 'Scan to learn more',
    'sp.why.card1.title': 'High Exposure',
    'sp.why.card1.desc': 'Gain local brand exposure all season long to hundreds of families.',
    'sp.why.card2.title': 'Youth Impact',
    'sp.why.card2.desc': 'Support the athletic and social development of a diverse community.',
    'sp.why.card3.title': 'Family Network',
    'sp.why.card3.desc': 'Connect your business directly with motivated parents and local leaders.',
    'sp.why.card4.title': 'Exclusive Access',
    'sp.why.card4.desc': 'Limited sponsorship slots ensure your brand remains prominent.',
    'sp.pkg.diamond': 'Diamond Shirt Sponsor',
    'sp.pkg.gold': 'Gold Sleeve Sponsor',
    'sp.pkg.bundle': 'Bundle Package (Best Value)',
    'sp.pkg.hudl': 'Hudl Live Stream Sponsor',
    'sp.pkg.flag': 'Flag Sponsor',
    'sp.pkg.banner': 'Field Banner Sponsor',
    'sp.pkg.investment': 'Investment',
    'sp.pkg.perYear': '/year',
    'sp.pkg.annual': 'Annual Investment',
    'sp.pkg.min2years': 'minimum 2-year agreement',
    'sp.pkg.total': 'Total Investment',
    'sp.pkg.viewPreview': 'View Preview',
    'sp.pkg.closeDetails': 'Close details',
  },
  pt: {
    // Navbar
    'nav.home': 'Início',
    'nav.about': 'Sobre',
    'nav.programs': 'Programas',
    'nav.sponsorship': 'Patrocínio',
    'nav.resources': 'Recursos',
    'nav.tryouts': 'Seletivas',
    'nav.contact': 'Contato',
    'nav.register': 'Inscreva-se',

    // Resources Page
    'resources.title': 'Recursos para Pais e Jogadores',
    'resources.subtitle': 'Documentos importantes, políticas e informações para as famílias de nossa academia.',
    'resources.doc1.title': 'Zero Tolerance Approved',
    'resources.doc1.desc': 'Nossas diretrizes sobre comportamento, política de tolerância zero e expectativas para jogadores, pais e treinadores.',
    'resources.doc2.title': 'Age Group Formation',
    'resources.doc2.desc': 'Informações sobre a formação de grupos por faixa etária e caminhos de desenvolvimento do jogador.',
    'resources.viewBtn': 'Ver Documento',
    
    // Hero Section
    'hero.title1': 'Onde Campeões',
    'hero.title2': 'São Construídos',
    'hero.subtitle': 'Desenvolvimento de futebol juvenil de elite na região de Charleston, SC',
    'hero.cta.primary': 'Inscreva-se Agora',
    'hero.cta.secondary': 'Ver Programas',
    'hero.marquee.1': 'Academia Júnior',
    'hero.marquee.2': 'Seleção',
    'hero.marquee.3': 'Elite',
    'hero.marquee.4': 'Futsal',
    'hero.marquee.5': 'Acampamentos de Verão',
    'hero.marquee.6': 'U4 AO U18',
    
    // AcademyHeroVisual
    'visual.quote': 'Desenvolvendo a próxima geração de jogadores.',
    'visual.card1.title': 'Treinamento',
    'visual.card1.subtitle': 'de Elite',
    'visual.card3.title': 'Caminho Profissional',
    
    // Lead Form
    'form.title': 'Entre em Contato',
    'form.subtitle': 'Interessado em se juntar à BISA? Preencha o formulário abaixo e nossa equipe entrará em contato.',
    'form.parentName': 'Nome do Responsável',
    'form.email': 'Endereço de E-mail',
    'form.phone': 'Número de Telefone',
    'form.playerName': 'Nome do Jogador',
    'form.birthYear': 'Ano de Nascimento do Jogador',
    'form.program': 'Programa de Interesse',
    'form.program.notSure': 'Ainda não tenho certeza',
    'form.message': 'Mensagem / Dúvidas',
    'form.messagePlaceholder': 'Como podemos ajudar?',
    'form.submit': 'Enviar Mensagem',
    'form.success.title': 'Mensagem Enviada!',
    'form.success.message': 'Obrigado por entrar em contato. Retornaremos em breve.',
    'form.success.button': 'Enviar outra mensagem',
    'form.error': 'Houve um erro ao enviar sua mensagem. Por favor, tente novamente mais tarde.',

    // Projeto BILU
    'projetobilu.label': '// PROJETO SOCIAL',
    'projetobilu.title': 'O Futebol Que Transforma Vidas',
    'projetobilu.subtitle': 'Projeto BILU é uma iniciativa humanitária global que usa o futebol como ferramenta de transformação social, presente em 10 países e impactando 15 mil crianças em todo o mundo, sendo 12 mil apenas no Brasil.',
    'projetobilu.stat1.value': '15k+',
    'projetobilu.stat1.label': 'Crianças no Mundo',
    'projetobilu.stat2.value': '12k+',
    'projetobilu.stat2.label': 'Crianças no Brasil',
    'projetobilu.stat3.value': '10',
    'projetobilu.stat3.label': 'Países',
    'projetobilu.stat4.value': '23',
    'projetobilu.stat4.label': 'Núcleos',
    'projetobilu.stat5.value': '153+',
    'projetobilu.stat5.label': 'Voluntários',
    'projetobilu.cta': 'Conheça o Projeto',

    // Academy CTA
    'academycta.title': 'Pronto para Elevar Seu Jogo?',
    'academycta.subtitle': 'Junte-se à principal academia de futebol juvenil em Charleston',
    'academycta.btn': 'Explorar Programas',
    'academycta.badge1': 'Metodologia Global Elite',
    'academycta.badge2': 'Treinadores Profissionais',
    'academycta.badge3': 'Programas U4 a U18',

    // Sponsors
    'sponsors.title': 'Patrocinadores e Parceiros',
    'sponsors.subtitle': 'Apoiados com orgulho por organizações que acreditam no poder do desenvolvimento juvenil e na transformação social.',
    'sponsors.comingSoon': 'Em Breve',
    'sponsors.becomePartner': 'Seja um Parceiro',

    // Projeto BILU Page
    'pb.hero.sub1': 'Futebol como instrumento de',
    'pb.hero.sub2': 'transformação humana',
    'pb.scroll': 'Descubra',
    'pb.whatis.title': 'O Que É O ',
    'pb.whatis.titleHighlight': 'Projeto BILU?',
    'pb.whatis.p1': 'O Projeto BILU é uma iniciativa social global fundada pelo Coach PC que usa o futebol como ferramenta para garantir uma infância digna para crianças em situação de vulnerabilidade ao redor do mundo.',
    'pb.whatis.p2.1': 'Atuamos com núcleos permanentes em ',
    'pb.whatis.p2.2': '10 países',
    'pb.whatis.p2.3': ' e campanhas humanitárias pontuais em outros ',
    'pb.whatis.p2.4': '13',
    'pb.whatis.p2.5': ', com um exército de voluntários apaixonados por transformar vidas.',
    'pb.numbers.title': 'Impacto em Números',
    'pb.numbers.l1': 'Países com Núcleos',
    'pb.numbers.l2': 'Países com Ações Pontuais',
    'pb.numbers.l3': 'Países Alcançados',
    'pb.numbers.l4': 'Voluntários (Somente BR)',
    'pb.numbers.l5': 'Núcleos no Brasil',
    'pb.global.title': 'Presença Global',
    'pb.global.desc': 'Onde operamos nossos 10 núcleos permanentes promovendo a inclusão pelo esporte.',
    'pb.global.otherTitle': 'Ações Humanitárias Pontuais em 13 Países',
    'pb.global.otherDesc': 'Bolívia, Colômbia, Uruguai, Paraguai, Costa Rica, El Salvador, Nicarágua, Senegal, Moçambique, Angola, Guiné-Bissau e mais 2...',
    'pb.brazil.title': 'Brasil em Detalhes',
    'pb.brazil.desc': 'Distribuição dos nossos 17 núcleos ao longo do território brasileiro.',
    'pb.brazil.centers': 'Núcleos',
    'pb.brazil.volunteers': 'Voluntários',
    'pb.actions.title': 'O Que Fazemos',
    'pb.actions.1.title': 'Natal Solidário',
    'pb.actions.1.desc': 'Ações de arrecadação e entrega de brinquedos e alimentos para famílias vulneráveis.',
    'pb.actions.2.title': 'Páscoa Feliz',
    'pb.actions.2.desc': 'Distribuição de chocolates e mensagens de esperança nas comunidades apoiadas.',
    'pb.actions.3.title': 'Projetos Sociais',
    'pb.actions.3.desc': 'Ações contínuas junto à comunidade trabalhando as bases morais, educacionais e civis.',
    'pb.actions.4.title': 'Campanhas Humanitárias',
    'pb.actions.4.desc': 'Suporte e ajuda humanitária em regiões impactadas por crises e desastres pelo mundo.',
    'pb.actions.5.title': 'Desenvolvimento Infantil',
    'pb.actions.5.desc': 'O futebol como a principal ferramenta mestra no desenvolvimento físico e cognitivo da criança.',
    'pb.gallery.title': 'Nossa Galeria',
    'pb.gallery.desc': 'Momentos inesquecíveis nos nossos núcleos pelo Brasil e pelo mundo.',
    'pb.gallery.soon': 'Em Breve',
    'pb.cta.title': 'Faça Parte dessa Transformação',
    'pb.cta.btn1': 'Seja Voluntário',
    'pb.cta.btn2': 'Voltar para o Site',

    // Summer Camps Page
    'sc.hero.badge': 'JUNHO E JULHO · SANGAREE MIDDLE SCHOOL',
    'sc.hero.title1': 'BISA',
    'sc.hero.title2': 'SUMMER CAMPS',
    'sc.hero.subtitle': 'Dois treinos por semana. Um torneio interno. Um verão que seu filho nunca esquecerá.',
    'sc.hero.btn1': 'GARANTA SUA VAGA \u2192',
    'sc.hero.btn2': 'VER DETALHES DO PROGRAMA',
    
    'sc.ticker.1': 'Sangaree Middle School',
    'sc.ticker.2': 'Junho e Julho',
    'sc.ticker.3': '2x Por Semana',
    'sc.ticker.4': 'Torneio Interno',
    'sc.ticker.5': 'Vagas Limitadas',
    'sc.ticker.6': 'Inscrições Abertas',

    'sc.overview.badge': 'O Programa',
    'sc.overview.title': 'VISÃO DO PROGRAMA',
    'sc.ov.1.title': 'Junho e Julho',
    'sc.ov.1.desc': 'Dois meses inteiros de desenvolvimento de futebol de elite',
    'sc.ov.2.title': 'Sangaree Middle School',
    'sc.ov.2.desc': 'Localização conveniente, segura e familiar',
    'sc.ov.3.title': '2x Por Semana',
    'sc.ov.3.desc': 'Ritmo de treinamento consistente que constrói habilidades reais',
    'sc.ov.4.title': 'Torneio Interno',
    'sc.ov.4.desc': 'Competição, vitórias e crescimento — tudo dentro da comunidade do acampamento',

    'sc.features.title': 'O QUE O SEU FILHO VAI EXPERIMENTAR',
    'sc.feat.1.title': 'Treinamento de Elite',
    'sc.feat.1.desc': 'Treinadores certificados com experiência internacional e paixão real pelo desenvolvimento de jogadores',
    'sc.feat.2.title': 'Desenvolvimento de Habilidades',
    'sc.feat.2.desc': 'Treinamento técnico, tático e físico adaptado a todas as idades e níveis',
    'sc.feat.3.title': 'Cultura de Equipe',
    'sc.feat.3.desc': 'Construir amizades, aprender a se comunicar e crescer como parte de uma verdadeira equipe',
    'sc.feat.4.title': 'Torneio Interno',
    'sc.feat.4.desc': 'Todo jogador compete no nosso campeonato interno — o grande destaque do acampamento',
    'sc.feat.5.title': 'Ambiente Seguro',
    'sc.feat.5.desc': 'Supervisão total, atmosfera inclusiva e cuidado com cada indivíduo',
    'sc.feat.6.title': 'Memórias de Verão',
    'sc.feat.6.desc': 'Brincadeiras, risadas e crescimento — uma experiência muito além do campo',

    'sc.global.title1': 'UMA COMUNIDADE GLOBAL, ',
    'sc.global.title2': 'TREINANDO JUNTA',
    'sc.global.desc': 'Nossos jogadores vêm de todas as partes do mundo — o futebol é a única linguagem que importa.',

    'sc.join.title1': 'COMO ',
    'sc.join.title2': 'PARTICIPAR',
    'sc.step.1.num': '01',
    'sc.step.1.title': 'Clique em Registrar',
    'sc.step.1.desc': 'Aperte o botão e preencha o rápido formulário de inscrição no PlayMetrics',
    'sc.step.2.num': '02',
    'sc.step.2.title': 'Confirme sua Vaga',
    'sc.step.2.desc': 'Você receberá uma confirmação com todos os detalhes sobre localização e cronograma',
    'sc.step.3.num': '03',
    'sc.step.3.title': 'Esteja Preparado',
    'sc.step.3.desc': 'Traga as chuteiras, as caneleiras e sua melhor atitude — do resto a gente cuida',
    'sc.step.4.num': '04',
    'sc.step.4.title': 'Jogue. Compita. Cresça.',
    'sc.step.4.desc': 'Treine duas vezes por semana e participe do nosso torneio interno',
    'sc.join.btn': 'REGISTRE-SE AGORA \u2192',

    'sc.faq.title': 'PERGUNTAS FREQUENTES',
    'sc.faq.1.q': 'Quem pode participar?',
    'sc.faq.1.a': 'O acampamento é aberto a jogadores de todos os níveis de habilidade. Se seu filho ama futebol, o lugar dele é aqui.',
    'sc.faq.2.q': 'Onde exatamente é o acampamento?',
    'sc.faq.2.a': 'Sangaree Middle School. O endereço e detalhes do estacionamento serão enviados após a inscrição.',
    'sc.faq.3.q': 'Com que frequência são os treinos?',
    'sc.faq.3.a': 'Duas vezes por semana durante junho e julho.',
    'sc.faq.4.q': 'O que é o Torneio Interno?',
    'sc.faq.4.a': 'No final do acampamento, todos os jogadores competem num campeonato interno organizado dentro da nossa própria comunidade do acampamento.',
    'sc.faq.5.q': 'O que o meu filho deve levar?',
    'sc.faq.5.a': 'Chuteiras, caneleiras, meião, garrafa de água e roupas de treino. Uma lista completa é enviada por e-mail após a inscrição.',
    'sc.faq.6.q': 'Como faço para me inscrever?',
    'sc.faq.6.a': 'Clique em qualquer botão de Registro nesta página para ser redirecionado para nosso formulário seguro de inscrição no PlayMetrics.',

    'sc.cta.badge': 'Não espere',
    'sc.cta.title': 'NÃO DEIXE SEU FILHO PERDER ESTE VERÃO',
    'sc.cta.subtitle': 'Vagas limitadas. Junho e Julho no Sangaree Middle School.',
    'sc.cta.btn': 'REGISTRE-SE AGORA \u2192',
    'sc.cta.micro': 'Inscrição rápida pelo PlayMetrics · Seguro e fácil',

    // Sponsorship Page
    'sp.hero.title1': 'PATROCÍNIO DE',
    'sp.hero.title2': 'CLUBES',
    'sp.hero.scroll': 'Role para explorar',
    'sp.hero.quote': '"Você não está apenas colocando seu logotipo no campo — você está abrindo portas para jovens jogadores talentosos que, graças ao seu apoio, podem perseguir seus sonhos e construir uma vida melhor através do esporte."',
    'sp.impact.title': 'Mais Que Patrocínio.',
    'sp.impact.titleHighlight': 'É Transformação.',
    'sp.impact.desc': 'Ao se tornar um patrocinador, você não está apenas apoiando a academia — você está ajudando a BISA a continuar sua missão de criar oportunidades reais para crianças em todo o mundo.',
    'sp.impact.callout': 'Graças ao apoio dos patrocinadores, a BISA cresceu de $7.214 em ajuda financeira para mais de $50.000 nesta temporada.',
    'sp.impact.stat.current': 'Temporada Atual',
    'sp.impact.footer': 'Cada contribuição ajuda crianças de diferentes países a terem acesso ao futebol, educação e experiências que transformam vidas.',
    'sp.jersey.badge': '✨ Patrocínio Premium',
    'sp.jersey.title1': 'Patrocínio de',
    'sp.jersey.title2': 'Camisa Oficial',
    'sp.jersey.front': 'Frente — Patrocinador Master',
    'sp.jersey.sleeve': 'Costas/Manga — Patrocinador de Manga',
    'sp.jersey.benefit1': 'Seu logo nas camisas de competição — visibilidade máxima',
    'sp.jersey.benefit2': 'Presença constante em fotos, vídeos e redes sociais',
    'sp.jersey.benefit3': 'Financiamento direto para bolsas de estudo de atletas',
    'sp.jersey.benefit4': 'Associação total com uma marca focada na comunidade',
    'sp.packages.transitionTitle1': 'PACOTES DE PATROCÍNIO',
    'sp.packages.transitionTitle2': 'DISPONÍVEIS',
    'sp.bundle.badge': 'A Conexão Suprema',
    'sp.bundle.title1': 'BISA BUNDLE',
    'sp.bundle.title2': 'PACKAGE',
    'sp.bundle.desc': 'Por que se contentar com um quando você pode dominar em todas as frentes? Nosso Pacote Bundle combina todos os ativos de campo e digitais para o máximo impacto na comunidade.',
    'sp.bundle.benefit.hudl': 'Anúncios Hudl Live',
    'sp.bundle.hudl.chk1': 'Banner de publicidade digital',
    'sp.bundle.hudl.chk2': 'Alcance de transmissão ao vivo',
    'sp.bundle.hudl.chk3': 'Exposição global das famílias',
    'sp.bundle.hudl.chk4': 'Reconhecimento digital da marca',
    'sp.bundle.benefit.banner': 'Banner de Campo (8x4)',
    'sp.bundle.banner.chk1': 'Tamanho padrão 8\' x 4\'',
    'sp.bundle.banner.chk2': 'Posicionamento de campo premium',
    'sp.bundle.banner.chk3': 'Visibilidade diária dos pais',
    'sp.bundle.banner.chk4': 'Tráfego direto por QR Code',
    'sp.bundle.benefit.flag': 'Bandeira do Clube (Evento)',
    'sp.bundle.flag.chk1': 'Bandeira vertical com marca',
    'sp.bundle.flag.chk2': 'Presença móvel em eventos',
    'sp.bundle.flag.chk3': 'Visibilidade em torneios',
    'sp.bundle.flag.chk4': 'Branding em múltiplos locais',
    'sp.bundle.benefit.priority': 'Colocação Prioritária',
    'sp.bundle.asset.checklist': 'CHECKLIST DO ATIVO:',
    'sp.bundle.asset.quote': 'Este ativo é meticulosamente projetado para representar sua marca durante as horas de pico de atividade, garantindo que cada pai e atleta reconheça sua contribuição para a academia.',
    'sp.bundle.save': 'ESPECIAL ECONOMIZE $1.000',
    'sp.hudl.badge': '🎥 Presença Digital',
    'sp.hudl.title': 'Transmissão ao Vivo Hudl',
    'sp.hudl.desc': 'Sua marca em destaque durante cada jogo transmitido ao vivo. Alcance famílias, fãs e apoiadores em qualquer lugar do mundo.',
    'sp.flag.badge': 'Branding Premium',
    'sp.flag.title': 'Patrocínio de Bandeira',
    'sp.flag.desc': 'Uma bandeira vertical de alta visibilidade com sua marca, exibida com destaque no centro de treinamento e levada para todos os jogos do clube.',
    'sp.banner.badge': 'Presença de Campo',
    'sp.banner.title': 'Patrocínio de Banner',
    'sp.banner.desc': 'Banner de 8\' x 4\' estrategicamente posicionado em nosso campo de treinamento, visto diariamente por pais e atletas.',
    'sp.why.badge': 'Comunidade e Crescimento',
    'sp.why.title': 'Por que ser Parceiro da BISA?',
    'sp.why.stat.athletes': 'Atletas',
    'sp.why.stat.families': 'Famílias',
    'sp.why.stat.weekly': 'Alcance Semanal',
    'sp.why.stat.coverage': 'Cobertura Social',
    'sp.packages.title1': 'Escolha seu',
    'sp.packages.title2': 'Pacote',
    'sp.packages.desc': 'Oportunidades exclusivas para mostrar sua marca enquanto apoia o desenvolvimento atlético e social de jovens jogadores.',
    'sp.nonprofit.title': 'Organização Sem Fins Lucrativos 501(c)(3)',
    'sp.nonprofit.desc': 'A Bilu International Soccer Academy é uma organização sem fins lucrativos registrada 501(c)(3). Quaisquer doações ou patrocínios podem ser dedutíveis de impostos. Sinta-se à vontade para solicitar um recibo ou carta para fins fiscais.',
    'sp.cta.title1': 'SEU LOGO ESTARÁ AO LADO',
    'sp.cta.title2': 'DA EXCELÊNCIA ESPORTIVA',
    'sp.cta.subtitle': 'ENTRE EM CONTATO PARA GARANTIR SEU ESPAÇO!',
    'sp.contact.info': 'Informações de Contato',
    'sp.contact.more': 'Informações Adicionais',
    'sp.contact.visit': 'Visite nosso site',
    'sp.contact.scan': 'Escaneie para saber mais',
    'sp.why.card1.title': 'Alta Exposição',
    'sp.why.card1.desc': 'Obtenha exposição de marca local durante toda a temporada para centenas de famílias.',
    'sp.why.card2.title': 'Impacto Juvenil',
    'sp.why.card2.desc': 'Apoie o desenvolvimento atlético e social de uma comunidade diversificada.',
    'sp.why.card3.title': 'Rede Familiar',
    'sp.why.card3.desc': 'Conecte sua empresa diretamente com pais motivados e líderes locais.',
    'sp.why.card4.title': 'Acesso Exclusivo',
    'sp.why.card4.desc': 'Slots de patrocínio limitados garantem que sua marca permaneça em destaque.',
    'sp.pkg.diamond': 'Patrocinador de Camisa Diamond',
    'sp.pkg.gold': 'Patrocinador de Manga Gold',
    'sp.pkg.bundle': 'Pacote Bundle (Melhor Valor)',
    'sp.pkg.hudl': 'Patrocinador de Transmissão Hudl',
    'sp.pkg.flag': 'Patrocinador de Bandeira',
    'sp.pkg.banner': 'Patrocinador de Banner de Campo',
    'sp.pkg.investment': 'Investimento',
    'sp.pkg.perYear': '/ano',
    'sp.pkg.annual': 'Investimento Anual',
    'sp.pkg.min2years': 'contrato mínimo de 2 anos',
    'sp.pkg.total': 'Investimento Total',
    'sp.pkg.viewPreview': 'Ver Prévia',
    'sp.pkg.closeDetails': 'Fechar detalhes',
  },
  es: {
    // Navbar
    'nav.home': 'Inicio',
    'nav.about': 'Nosotros',
    'nav.programs': 'Programas',
    'nav.sponsorship': 'Patrocinio',
    'nav.resources': 'Recursos',
    'nav.tryouts': 'Pruebas',
    'nav.contact': 'Contacto',
    'nav.register': 'Regístrate',

    // Resources Page
    'resources.title': 'Recursos para Padres y Jugadores',
    'resources.subtitle': 'Documentos importantes, políticas e información para las familias de nuestra academia.',
    'resources.doc1.title': 'Zero Tolerance Approved',
    'resources.doc1.desc': 'Nuestras directrices sobre comportamiento, política de tolerancia cero y expectativas para jugadores, padres y entrenadores.',
    'resources.doc2.title': 'Age Group Formation',
    'resources.doc2.desc': 'Información sobre la formación de grupos por edad y los caminos de desarrollo del jugador.',
    'resources.viewBtn': 'Ver Documento',
    
    // Hero Section
    'hero.title1': 'Donde los Campeones',
    'hero.title2': 'Se Construyen',
    'hero.subtitle': 'Desarrollo de fútbol juvenil de élite en el área de Charleston, SC',
    'hero.cta.primary': 'Regístrate Ahora',
    'hero.cta.secondary': 'Ver Programas',
    'hero.marquee.1': 'Academia Junior',
    'hero.marquee.2': 'Selección',
    'hero.marquee.3': 'Élite',
    'hero.marquee.4': 'Futsal',
    'hero.marquee.5': 'Campamentos de Verano',
    'hero.marquee.6': 'U4 AL U18',
    
    // AcademyHeroVisual
    'visual.quote': 'Desarrollando la próxima generación de jugadores.',
    'visual.card1.title': 'Entrenamiento',
    'visual.card1.subtitle': 'de Élite',
    'visual.card3.title': 'Camino Profesional',
    
    // Lead Form
    'form.title': 'Ponte en Contacto',
    'form.subtitle': '¿Interesado en unirte a BISA? Completa el formulario a continuación y nuestro equipo se comunicará contigo.',
    'form.parentName': 'Nombre del Padre/Tutor',
    'form.email': 'Correo Electrónico',
    'form.phone': 'Número de Teléfono',
    'form.playerName': 'Nombre del Jugador',
    'form.birthYear': 'Año de Nacimiento del Jugador',
    'form.program': 'Programa de Interés',
    'form.program.notSure': 'Aún no estoy seguro',
    'form.message': 'Mensaje / Preguntas',
    'form.messagePlaceholder': '¿Cómo podemos ayudarte?',
    'form.submit': 'Enviar Mensaje',
    'form.success.title': '¡Mensaje Enviado!',
    'form.success.message': 'Gracias por contactarnos. Nos comunicaremos contigo en breve.',
    'form.success.button': 'Enviar otro mensaje',
    'form.error': 'Hubo un error al enviar tu mensaje. Por favor, inténtalo de nuevo más tarde.',

    // Projeto BILU
    'projetobilu.label': '// PROYECTO SOCIAL',
    'projetobilu.title': 'El Fútbol Que Transforma Vidas',
    'projetobilu.subtitle': 'Proyecto BILU es una iniciativa humanitaria global que usa el fútbol como herramienta de transformación social, presente en 10 países e impactando a más de 15 mil niños en todo el mundo, con 12 mil solo en Brasil.',
    'projetobilu.stat1.value': '15k+',
    'projetobilu.stat1.label': 'Niños en el Mundo',
    'projetobilu.stat2.value': '12k+',
    'projetobilu.stat2.label': 'Niños en Brasil',
    'projetobilu.stat3.value': '10',
    'projetobilu.stat3.label': 'Países',
    'projetobilu.stat4.value': '23',
    'projetobilu.stat4.label': 'Centros',
    'projetobilu.stat5.value': '153+',
    'projetobilu.stat5.label': 'Voluntarios',
    'projetobilu.cta': 'Conoce el Proyecto',

    // Academy CTA
    'academycta.title': '¿Listo para Elevar tu Juego?',
    'academycta.subtitle': 'Únete a la principal academia de fútbol juvenil en Charleston',
    'academycta.btn': 'Explorar Programas',
    'academycta.badge1': 'Metodología Global Élite',
    'academycta.badge2': 'Entrenadores Profesionales',
    'academycta.badge3': 'Programas U4 a U18',

    // Sponsors
    'sponsors.title': 'Nuestros Socios y Patrocinadores',
    'sponsors.subtitle': 'Apoyados con orgullo por organizaciones que creen en el poder del desarrollo juvenil y la transformación social.',
    'sponsors.comingSoon': 'Próximamente',
    'sponsors.becomePartner': 'Conviértete en Socio',

    // Projeto BILU Page
    'pb.hero.sub1': 'El fútbol como instrumento de',
    'pb.hero.sub2': 'transformación humana',
    'pb.scroll': 'Descubre',
    'pb.whatis.title': '¿Qué es el ',
    'pb.whatis.titleHighlight': 'Proyecto BILU?',
    'pb.whatis.p1': 'El Proyecto BILU es una iniciativa social global fundada por el Coach PC que utiliza el fútbol como herramienta para garantizar una infancia digna a niños vulnerables en todo el mundo.',
    'pb.whatis.p2.1': 'Operamos con centros permanentes en ',
    'pb.whatis.p2.2': '10 países',
    'pb.whatis.p2.3': ' y campañas humanitarias puntuales en otros ',
    'pb.whatis.p2.4': '13',
    'pb.whatis.p2.5': ', con un ejército de voluntarios apasionados por transformar vidas.',
    'pb.numbers.title': 'Impacto en Números',
    'pb.numbers.l1': 'Países con Centros',
    'pb.numbers.l2': 'Países con Campañas',
    'pb.numbers.l3': 'Países Alcanzados',
    'pb.numbers.l4': 'Voluntarios (Solo BR)',
    'pb.numbers.l5': 'Centros en Brasil',
    'pb.global.title': 'Presencia Global',
    'pb.global.desc': 'Donde operamos nuestros 10 centros permanentes promoviendo la inclusión a través del deporte.',
    'pb.global.otherTitle': 'Campañas Humanitarias en 13 Países',
    'pb.global.otherDesc': 'Bolivia, Colombia, Uruguay, Paraguay, Costa Rica, El Salvador, Nicaragua, Senegal, Mozambique, Angola, Guinea-Bisáu y 2 más...',
    'pb.brazil.title': 'Brasil en Detalle',
    'pb.brazil.desc': 'Distribución de nuestros 17 centros a lo largo del territorio brasileño.',
    'pb.brazil.centers': 'Centros',
    'pb.brazil.volunteers': 'Voluntarios',
    'pb.actions.title': 'Lo Que Hacemos',
    'pb.actions.1.title': 'Navidad Solidaria',
    'pb.actions.1.desc': 'Recolección y entrega de juguetes y alimentos para familias vulnerables.',
    'pb.actions.2.title': 'Feliz Pascua',
    'pb.actions.2.desc': 'Distribución de chocolates y mensajes de esperanza en las comunidades apoyadas.',
    'pb.actions.3.title': 'Proyectos Sociales',
    'pb.actions.3.desc': 'Acciones comunitarias continuas trabajando en bases morales, educativas y cívicas.',
    'pb.actions.4.title': 'Campañas Humanitarias',
    'pb.actions.4.desc': 'Apoyo y ayuda humanitaria en regiones afectadas por crisis y desastres en todo el mundo.',
    'pb.actions.5.title': 'Desarrollo Infantil',
    'pb.actions.5.desc': 'El fútbol como herramienta principal en el desarrollo físico y cognitivo infantil.',
    'pb.gallery.title': 'Nuestra Galería',
    'pb.gallery.desc': 'Momentos inolvidables en nuestros centros por Brasil y el mundo.',
    'pb.gallery.soon': 'Próximamente',
    'pb.cta.title': 'Sé Parte de esta Transformación',
    'pb.cta.btn1': 'Sé un Voluntario',
    'pb.cta.btn2': 'Volver al Sitio',

    // Summer Camps Page
    'sc.hero.badge': 'JUNIO Y JULIO · SANGAREE MIDDLE SCHOOL',
    'sc.hero.title1': 'BISA',
    'sc.hero.title2': 'SUMMER CAMPS',
    'sc.hero.subtitle': 'Dos entrenamientos por semana. Un torneo interno. Un verano que tu hijo nunca olvidará.',
    'sc.hero.btn1': 'ASEGURA TU LUGAR \u2192',
    'sc.hero.btn2': 'VER DETALLES DEL PROGRAMA',
    
    'sc.ticker.1': 'Sangaree Middle School',
    'sc.ticker.2': 'Junio y Julio',
    'sc.ticker.3': '2x Por Semana',
    'sc.ticker.4': 'Torneo Interno',
    'sc.ticker.5': 'Cupos Limitados',
    'sc.ticker.6': 'Inscripciones Abiertas',

    'sc.overview.badge': 'El Programa',
    'sc.overview.title': 'RESUMEN DEL PROGRAMA',
    'sc.ov.1.title': 'Junio y Julio',
    'sc.ov.1.desc': 'Dos meses completos de desarrollo de fútbol de élite',
    'sc.ov.2.title': 'Sangaree Middle School',
    'sc.ov.2.desc': 'Ubicación conveniente, segura y familiar',
    'sc.ov.3.title': '2x Por Semana',
    'sc.ov.3.desc': 'Ritmo de entrenamiento constante que construye habilidades reales',
    'sc.ov.4.title': 'Torneo Interno',
    'sc.ov.4.desc': 'Compite, gana, crece — todo dentro de la comunidad del campamento',

    'sc.features.title': 'LO QUE EXPERIMENTARÁ TU HIJO',
    'sc.feat.1.title': 'Entrenamiento de Élite',
    'sc.feat.1.desc': 'Entrenadores certificados con experiencia internacional y verdadera pasión por el desarrollo',
    'sc.feat.2.title': 'Desarrollo de Habilidades',
    'sc.feat.2.desc': 'Entrenamiento técnico, táctico y físico adaptado a todas las edades y niveles',
    'sc.feat.3.title': 'Cultura de Equipo',
    'sc.feat.3.desc': 'Construir amistades, aprender a comunicarse y crecer como parte de un verdadero equipo',
    'sc.feat.4.title': 'Torneo Interno',
    'sc.feat.4.desc': 'Cada jugador compite en nuestro campeonato interno — lo más destacado del campamento',
    'sc.feat.5.title': 'Entorno Seguro',
    'sc.feat.5.desc': 'Supervisión completa, ambiente inclusivo y cuidado individual',
    'sc.feat.6.title': 'Recuerdos de Verano',
    'sc.feat.6.desc': 'Juegos, risas y crecimiento — una experiencia que va mucho más allá de la cancha',

    'sc.global.title1': 'UNA COMUNIDAD GLOBAL, ',
    'sc.global.title2': 'ENTRENANDO JUNTOS',
    'sc.global.desc': 'Nuestros jugadores provienen de todas partes del mundo — el fútbol es el único lenguaje que importa.',

    'sc.join.title1': 'CÓMO ',
    'sc.join.title2': 'UNIRSE',
    'sc.step.1.num': '01',
    'sc.step.1.title': 'Haz Clic en Registrar',
    'sc.step.1.desc': 'Presiona el botón y completa el rápido formulario de registro en PlayMetrics',
    'sc.step.2.num': '02',
    'sc.step.2.title': 'Confirma tu Asiento',
    'sc.step.2.desc': 'Recibirás una confirmación con todos los detalles de ubicación y horarios',
    'sc.step.3.num': '03',
    'sc.step.3.title': 'Llega Preparado',
    'sc.step.3.desc': 'Trae tacos, espinilleras y tu mejor actitud — nosotros nos encargamos del resto',
    'sc.step.4.num': '04',
    'sc.step.4.title': 'Juega. Compite. Crece.',
    'sc.step.4.desc': 'Entrena dos veces por semana y compite en nuestro torneo.',
    'sc.join.btn': 'REGÍSTRATE AHORA \u2192',

    'sc.faq.title': 'PREGUNTAS FRECUENTES',
    'sc.faq.1.q': '¿Quién puede participar?',
    'sc.faq.1.a': 'El campamento está abierto a jugadores de todos los niveles de habilidad. Si a tu hijo le encanta el fútbol, su lugar está aquí.',
    'sc.faq.2.q': '¿Dónde es exactamente el campamento?',
    'sc.faq.2.a': 'Sangaree Middle School. La dirección y los detalles de estacionamiento se envían después del registro.',
    'sc.faq.3.q': '¿Con qué frecuencia son las sesiones?',
    'sc.faq.3.a': 'Dos veces por semana durante junio y julio.',
    'sc.faq.4.q': '¿Qué es el Torneo Interno?',
    'sc.faq.4.a': 'Al final del campamento, todos los jugadores compiten en un campeonato interno organizado dentro de la propia comunidad del camp.',
    'sc.faq.5.q': '¿Qué debe llevar mi hijo/a?',
    'sc.faq.5.a': 'Tacos, espinilleras, calcetines, botella de agua y ropa deportiva. Se enviará una lista completa por email tras registrarte.',
    'sc.faq.6.q': '¿Cómo me inscribo?',
    'sc.faq.6.a': 'Haz clic en cualquier botón de Registro de esta página para ir a nuestro formulario seguro en PlayMetrics.',

    'sc.cta.badge': 'No esperes',
    'sc.cta.title': 'NO DEJES QUE TU HIJO SE PIERDA ESTE VERANO',
    'sc.cta.subtitle': 'Cupos limitados. Junio y Julio en Sangaree Middle School.',
    'sc.cta.btn': 'REGÍSTRATE AHORA \u2192',
    'sc.cta.micro': 'Inscripción rápida a través de PlayMetrics · Seguro y fácil',

    // Sponsorship Page
    'sp.hero.title1': 'PATROCINIO DE',
    'sp.hero.title2': 'CLUBES',
    'sp.hero.scroll': 'Desliza para explorar',
    'sp.hero.quote': '"No solo estás colocando tu logo en el campo — estás abriendo puertas a jóvenes jugadores talentosos que, gracias a tu apoyo, podem perseguir sus sueños y construir una vida mejor a través del deporte."',
    'sp.impact.title': 'Más que Patrocinio.',
    'sp.impact.titleHighlight': 'Es Transformación.',
    'sp.impact.desc': 'Al convertirte en patrocinador, no solo estás apoyando a la academia — estás ayudando a BISA a continuar sua misión de crear oportunidades reales para niños en todo el mundo.',
    'sp.impact.callout': 'Gracias al apoyo de los patrocinadores, BISA ha crecido de $7,214 en ayuda financiera a más de $50,000 esta temporada.',
    'sp.impact.stat.current': 'Temporada Actual',
    'sp.impact.footer': 'Cada contribución ayuda a niños de diferentes países a acceder al fútbol, la educación y experiencias que cambian vidas.',
    'sp.jersey.badge': '✨ Patrocinio Premium',
    'sp.jersey.title1': 'Patrocinio de',
    'sp.jersey.title2': 'Camiseta Oficial',
    'sp.jersey.front': 'Frente — Patrocinador Principal',
    'sp.jersey.sleeve': 'Espalda/Manga — Patrocinador de Manga',
    'sp.jersey.benefit1': 'Tu logo en las camisetas de competición — máxima visibilidad',
    'sp.jersey.benefit2': 'Presencia constante en fotos, videos y redes sociales',
    'sp.jersey.benefit3': 'Financiación directa para becas de estudiantes-atletas',
    'sp.jersey.benefit4': 'Asociación total con una marca centrada en la comunidad',
    'sp.packages.transitionTitle1': 'PAQUETES DE PATROCINIO',
    'sp.packages.transitionTitle2': 'DISPONIBLES',
    'sp.bundle.badge': 'La Conexión Definitiva',
    'sp.bundle.title1': 'BISA BUNDLE',
    'sp.bundle.title2': 'PACKAGE',
    'sp.bundle.desc': '¿Por qué conformarse con uno cuando puedes dominar en todos los frentes? Nuestro Paquete Bundle combina todos los activos de campo y digitales para el máximo impacto en la comunidad.',
    'sp.bundle.benefit.hudl': 'Anuncios Hudl Live',
    'sp.bundle.hudl.chk1': 'Banner de publicidad digital',
    'sp.bundle.hudl.chk2': 'Alcance de transmisión en vivo',
    'sp.bundle.hudl.chk3': 'Exposición global a familias',
    'sp.bundle.hudl.chk4': 'Reconocimiento digital de la marca',
    'sp.bundle.benefit.banner': 'Banner de Campo (8x4)',
    'sp.bundle.banner.chk1': 'Tamaño estándar de 8\' x 4\'',
    'sp.bundle.banner.chk2': 'Posicionamiento de campo premium',
    'sp.bundle.banner.chk3': 'Visibilidad diaria de los padres',
    'sp.bundle.banner.chk4': 'Tráfico directo por código QR',
    'sp.bundle.benefit.flag': 'Bandera del Club (Evento)',
    'sp.bundle.flag.chk1': 'Bandera vertical con marca',
    'sp.bundle.flag.chk2': 'Presencia móvil en eventos',
    'sp.bundle.flag.chk3': 'Visibilidad en torneos',
    'sp.bundle.flag.chk4': 'Branding en múltiples ubicaciones',
    'sp.bundle.benefit.priority': 'Colocación Prioritaria',
    'sp.bundle.asset.checklist': 'CHECKLIST DEL ACTIVO:',
    'sp.bundle.asset.quote': 'Este activo está meticulosamente diseñado para representar su marca durante las horas de mayor actividad, asegurando que cada padre y atleta reconozca su contribución a la academia.',
    'sp.bundle.save': 'ESPECIAL AHORRA $1,000',
    'sp.hudl.badge': '🎥 Presencia Digital',
    'sp.hudl.title': 'Transmisión en Vivo Hudl',
    'sp.hudl.desc': 'Tu marca al frente y al centro durante cada partido transmitido en vivo. Llega a familias, fans y seguidores en cualquier parte del mundo.',
    'sp.flag.badge': 'Branding Premium',
    'sp.flag.title': 'Patrocinio de Bandera',
    'sp.flag.desc': 'Una bandera vertical de alta visibilidad con su marca, exhibida de manera destacada en el centro de entrenamiento y llevada a cada partido del club.',
    'sp.banner.badge': 'Presencia en el Campo',
    'sp.banner.title': 'Patrocinio de Banner',
    'sp.banner.desc': 'Banner de 8\' x 4\' posicionado estratégicamente en nuestro campo de entrenamiento, visto diariamente por padres y atletas.',
    'sp.why.badge': 'Comunidad y Crecimiento',
    'sp.why.title': '¿Por qué ser socio de BISA?',
    'sp.why.stat.athletes': 'Atletas',
    'sp.why.stat.families': 'Familias',
    'sp.why.stat.weekly': 'Alcance Semanal',
    'sp.why.stat.coverage': 'Cobertura Social',
    'sp.packages.title1': 'Elige tu',
    'sp.packages.title2': 'Paquete',
    'sp.packages.desc': 'Oportunidades exclusivas para mostrar su marca mientras apoya el desarrollo atlético y social de los jugadores jóvenes.',
    'sp.nonprofit.title': 'Organización sin Fines de Lucro 501(c)(3)',
    'sp.nonprofit.desc': 'Bilu International Soccer Academy es una organización sin fines de lucro registrada 501(c)(3). Cualquier donación o patrocinio puede ser deducible de impuestos. No dude en solicitar un recibo o carta para fines fiscales.',
    'sp.cta.title1': 'TU LOGO ESTARÁ AL LADO',
    'sp.cta.title2': 'DE LA EXCELENCIA DEPORTIVA',
    'sp.cta.subtitle': '¡CONTÁCTENOS PARA GARANTIZAR SU ESPACIO!',
    'sp.contact.info': 'Información de Contacto',
    'sp.contact.more': 'Más Información',
    'sp.contact.visit': 'Visite nuestro sitio web',
    'sp.contact.scan': 'Escanee para saber más',
    'sp.why.card1.title': 'Alta Exposición',
    'sp.why.card1.desc': 'Obtenga exposición de marca local durante toda la temporada para cientos de familias.',
    'sp.why.card2.title': 'Impacto Juvenil',
    'sp.why.card2.desc': 'Apoye el desarrollo atlético y social de una comunidad diversa.',
    'sp.why.card3.title': 'Red Familiar',
    'sp.why.card3.desc': 'Conecte su negocio directamente con padres motivados y líderes locales.',
    'sp.why.card4.title': 'Acceso Exclusivo',
    'sp.why.card4.desc': 'Los cupos de patrocinio limitados aseguran que su marca permanezca destacada.',
    'sp.pkg.diamond': 'Patrocinador de Camiseta Diamond',
    'sp.pkg.gold': 'Patrocinador de Manga Gold',
    'sp.pkg.bundle': 'Paquete Bundle (Mejor Valor)',
    'sp.pkg.hudl': 'Patrocinador de Transmisión Hudl',
    'sp.pkg.flag': 'Patrocinador de Bandera',
    'sp.pkg.banner': 'Patrocinador de Banner de Campo',
    'sp.pkg.investment': 'Inversión',
    'sp.pkg.perYear': '/año',
    'sp.pkg.annual': 'Inversión Anual',
    'sp.pkg.min2years': 'contrato mínimo de 2 años',
    'sp.pkg.total': 'Inversión Total',
    'sp.pkg.viewPreview': 'Ver Vista Previa',
    'sp.pkg.closeDetails': 'Cerrar detalles',
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    // Load saved language from localStorage if available
    const savedLang = localStorage.getItem('bisa_language') as Language;
    if (savedLang && ['en', 'pt', 'es'].includes(savedLang)) {
      // @ts-ignore
      // eslint-disable-next-line
      setLanguage(savedLang);
    }
    setMounted(true);
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('bisa_language', lang);
  };

  const t = (key: string): string => {
    // Return translation or fallback to key if not found
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
